### ISSUE TITLE
[BUG] Mouse(except Left click) and keyboard keys cant be used in ImGui

### ISSUE THREAD

**Issue by only1mf** [kbrddestroyer/CS2.KernelCheat#134]
**Describe the bug**
Mouse(except Left click) and keyboard keys cant be used/detected by ImGui

**To Reproduce**
Make an scroll bar or just open the Demo ImGui menu **(ImGui::ShowDemoWindow(); in a loop)** and there try to use your mouse scroll wheel to scroll down or up or go to the "Inputs & Focus" tab in the Demo ImGui and there you can see that it only picks up "MouseLeft" and nothing more then that

**Screenshots or screen records**
![image](https://github.com/user-attachments/assets/eec08c2f-9ee0-406d-ac2e-5b96ab19a857)

**Desktop (please complete the following information):**
 - OS: win10 pro
 - Version 22H2
 - ImGui version: 1.90.8

**Additional context**

**Comment by kbrddestroyer** [comment]
As I see WndProc processes overlay events incorrectly, so both ImGui and CS2 have some input lags

That can be both because of low tickrate on render thread and bugs in WndProc

**Comment by kbrddestroyer** [comment]
WELL WELL WELL **FUCK WINAPI**

Currently window will lose it's WS_EX_TRANSPARENT flag if GUI is on. That was the issue: **WS_EX_TRANSPARENT** it passing all events through (that's pretty obvious now)

**Comment by kbrddestroyer** [comment]
Not the best way to fix it tho
