### ISSUE TITLE
[BUG] Сервер возвратил ссылку

### ISSUE THREAD

**Issue by xxA1eksandrxx** [kbrddestroyer/CS2.KernelCheat#135]
Такая вот фигня...
![image](https://github.com/user-attachments/assets/5216e8d5-ab88-4b80-baca-d850ba376de6)

**Comment by kbrddestroyer** [comment]
Ты собрался из ветки с активатором где подключен Flask
Сделай билд из main

**Comment by xxA1eksandrxx** [comment]
я скачал собранный (release)

**Comment by kbrddestroyer** [comment]
Это странно может что-то просочилось в release, гляну

**Comment by xxA1eksandrxx** [comment]
проект уже с отредактированными смещениями?

**Comment by kbrddestroyer** [comment]
Недавно был мердж но пару дней назад обновилась контра, есть шанс что они устарели

Буду благодарен если сделаешь пр в main

**Comment by xxA1eksandrxx** [comment]
в чит входит esp?

**Comment by kbrddestroyer** [comment]
Если будут еще вопросы по функционалу или использованию то советую зайти в дискорд, в тикете лучше общаться по задаче

**Comment by kbrddestroyer** [comment]
https://otvet.mail.ru/question/189205256
