### ISSUE TITLE
Seems not working

### ISSUE THREAD

**Issue by Leksa667** [kbrddestroyer/CS2.KernelCheat#59]
I don't have try to edit, but for me it's not working, I map the driver with my custom mapper with manual load and i try but zero features works for me..

**Comment by Leksa667** [comment]
btw I can finish the integration of ImGui for you if you want

**Comment by kbrddestroyer** [comment]
Press "Attach" button with cs2 process running. You should get WinPAI's MessageBox that cheat had attachet to target process. After that you can use features

Also I'm not sure what's in release branch rn. Need to merge main after I finish Thread Management

Speaking of ImGui: you can fork this repo if you want and open a pull request to main branch.

Feel free to DM me if you have any other questions 
https://discord.com/invite/wFUmHRUmjR

**Comment by kbrddestroyer** [comment]
There were some CS2 updates so I guess release branch contains outdated offsets. I queued new build
